name: todo_list_provider
description: Creating a simple todo list using Provider
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.10.5

dependencies:
  bloc: 8.1.2
  provider: 6.0.5
  shared_preferences: 2.2.0
  equatable: 2.0.5
  uuid: 3.0.7
  meta: 1.9.1
  get_it: 7.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail: 1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
